import type { BrokerAccount } from "../api/client";

export const MAIN_BROKER_ID = "dhan";

export const defaultBrokers: BrokerAccount[] = [
  {
    id: "dhan",
    name: "Dhan",
    vendor: "Dhan",
    color: "#0f9d58",
    auth: "access_token",
    segments: ["EQ", "FNO"],
    main: true,
    connected: true,
    active: true,
    mode: "idle",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "CONNECTED",
    keyHint: "",
    liveFeed: false,
  },
  {
    id: "zerodha",
    name: "Zerodha Kite",
    vendor: "Zerodha",
    color: "#f6461a",
    auth: "api_key",
    segments: ["EQ", "FNO", "COM"],
    main: false,
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "kotak",
    name: "Kotak Neo",
    vendor: "Kotak",
    color: "#0033a0",
    auth: "oauth",
    segments: ["EQ", "FNO"],
    main: false,
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "fyers",
    name: "Fyers",
    vendor: "Fyers",
    color: "#111827",
    auth: "oauth",
    segments: ["EQ", "FNO"],
    main: false,
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "paper",
    name: "Paper Trading",
    vendor: "T2S",
    color: "#2f54eb",
    auth: "none",
    segments: ["EQ", "FNO"],
    main: false,
    connected: true,
    active: false,
    mode: "paper",
    clientId: "PAPER-001",
    funds: 1000000,
    marginUsed: 12000,
    status: "CONNECTED",
    keyHint: "",
  },
];

export function brokerName(brokers: BrokerAccount[] | undefined, id?: string) {
  return brokers?.find((item) => item.id === id)?.name || id || "Dhan";
}
