import type { BrokerAccount } from "../api/client";

export const defaultBrokers: BrokerAccount[] = [
  {
    id: "paper",
    name: "Paper Trading",
    vendor: "T2S",
    color: "#2f54eb",
    auth: "none",
    segments: ["EQ", "FNO"],
    connected: true,
    active: true,
    mode: "paper",
    clientId: "PAPER-001",
    funds: 1000000,
    marginUsed: 84200,
    status: "CONNECTED",
    keyHint: "",
  },
  {
    id: "zerodha",
    name: "Zerodha Kite",
    vendor: "Zerodha",
    color: "#f6461a",
    auth: "api_key",
    segments: ["EQ", "FNO", "COM"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "upstox",
    name: "Upstox",
    vendor: "Upstox",
    color: "#5a2dff",
    auth: "oauth",
    segments: ["EQ", "FNO"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "angel",
    name: "Angel One",
    vendor: "Angel One",
    color: "#c41e3a",
    auth: "api_key",
    segments: ["EQ", "FNO", "COM"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "dhan",
    name: "Dhan",
    vendor: "Dhan",
    color: "#0f9d58",
    auth: "access_token",
    segments: ["EQ", "FNO"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "fyers",
    name: "Fyers",
    vendor: "Fyers",
    color: "#111827",
    auth: "oauth",
    segments: ["EQ", "FNO"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "groww",
    name: "Groww",
    vendor: "Groww",
    color: "#00b386",
    auth: "api_key",
    segments: ["EQ", "FNO"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "fivepaisa",
    name: "5Paisa",
    vendor: "5Paisa",
    color: "#00a651",
    auth: "api_key",
    segments: ["EQ", "FNO"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "icici",
    name: "ICICI Direct",
    vendor: "Breeze",
    color: "#f37a20",
    auth: "api_key",
    segments: ["EQ", "FNO"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
  {
    id: "kotak",
    name: "Kotak Neo",
    vendor: "Kotak",
    color: "#0033a0",
    auth: "oauth",
    segments: ["EQ", "FNO"],
    connected: false,
    active: false,
    mode: "sandbox",
    clientId: "",
    funds: 0,
    marginUsed: 0,
    status: "DISCONNECTED",
    keyHint: "",
  },
];

export function brokerName(brokers: BrokerAccount[] | undefined, id?: string) {
  return brokers?.find((item) => item.id === id)?.name || id || "Paper";
}
