import type { Snapshot } from "./api";

export const fallbackSnapshot: Snapshot = {
  indices: [
    { symbol: "NIFTY 50", price: 24580.25, change: 125.4, changePct: 0.51, spark: [24420, 24580], future: 24602.4, vwap: 24571.15, prevClose: 24454.85 },
    { symbol: "BANKNIFTY", price: 52140.8, change: 210.15, changePct: 0.4, spark: [51880, 52141], future: 52186.4, vwap: 52118.7, prevClose: 51930.65 },
    { symbol: "FINNIFTY", price: 24890.5, change: 98.2, changePct: 0.4, spark: [24740, 24891], future: 24912.8, vwap: 24881.4, prevClose: 24792.3 },
    { symbol: "SENSEX", price: 80642.3, change: 312.8, changePct: 0.39, spark: [80210, 80642], future: 80718.6, vwap: 80610.2, prevClose: 80329.5 },
    { symbol: "INDIA VIX", price: 13.24, change: -0.42, changePct: -3.07, spark: [13.9, 13.24], future: 13.24, vwap: 13.3, prevClose: 13.66 },
  ],
  ohlc: { open: 24462.1, high: 24612.8, low: 24418.35, close: 24580.25 },
  dnaScores: [
    { label: "Trend", value: 86 },
    { label: "Momentum", value: 78 },
    { label: "Buy Pressure", value: 91 },
    { label: "Volatility", value: 34 },
  ],
  optionChain: [
    { strike: 24400, callLtp: 212.4, callChg: 8.2, putLtp: 38.15, putChg: -11.4 },
    { strike: 24500, callLtp: 142.75, callChg: 6.8, putLtp: 62.4, putChg: -8.1, atm: true },
    { strike: 24600, callLtp: 88.2, callChg: 4.1, putLtp: 104.55, putChg: -5.6 },
  ],
  algos: [
    { id: "a4", name: "NIFTY VWAP ATM", tag: "NIFTY VWAP", kind: "nifty-vwap", symbol: "NIFTY", instrument: "option", optionType: "CE", indicator: "VWAP", lots: 1, lotSize: 65, qty: 65, timeframe: "5m", slPct: 20, targetPct: 40, summary: "NIFTY VWAP ATM · 5m options · SL 20% / TGT 40%", status: "PAUSED", pnl: 0, winRate: 0, enabled: false, brokerId: "dhan", runMode: "live" },
    { id: "a5", name: "NIFTY 15m VWAP reversal", tag: "15m VWAP", kind: "nifty-vwap-reversal", symbol: "NIFTY", instrument: "option", optionType: "CE", indicator: "NIFTY_VWAP_REVERSAL", lots: 1, lotSize: 65, qty: 65, timeframe: "15m", slPct: 15, targetPct: 30, summary: "NIFTY 15m VWAP reversal · weekly ATM options · SL 15% / TGT 30%", status: "PAUSED", pnl: 0, winRate: 0, enabled: false, brokerId: "dhan", runMode: "live" },
    { id: "a6", name: "NIFTY 15m VWAP hedge", tag: "15m hedge", kind: "nifty-vwap-hedge", symbol: "NIFTY", instrument: "option", optionType: "CE", indicator: "NIFTY_VWAP_HEDGE", lots: 1, lotSize: 65, qty: 65, timeframe: "15m", slPct: 0, targetPct: 40, summary: "NIFTY 15m VWAP hedge · weekly ATM · 1 lot + 2 opposite · +40% / −20% / +5% account · daily LIVE 09:30 IST", status: "PAUSED", pnl: 0, winRate: 0, enabled: false, brokerId: "dhan", runMode: "live", dailyLiveIst: "09:30" },
  ],
  positions: [],
  signals: [],
  marketWatch: [
    { symbol: "NIFTY 50", ltp: 24580.25, chg: 0.51, volume: "182.4 Cr" },
    { symbol: "BANKNIFTY", ltp: 52140.8, chg: 0.4, volume: "96.1 Cr" },
    { symbol: "RELIANCE", ltp: 2984.2, chg: 1.12, volume: "48.2 L" },
    { symbol: "HDFCBANK", ltp: 1672.4, chg: 0.64, volume: "62.8 L" },
  ],
  featuredSignal: {
    action: "BUY",
    symbol: "",
    strategy: "",
    expiry: "—",
    confidence: 0,
    risk: "—",
    metrics: [
      { label: "VWAP", value: 0 },
      { label: "DEPTH", value: 0 },
      { label: "OI", value: 0 },
      { label: "VOLUME", value: 0 },
    ],
  },
  fiiDii: { fii: { buy: 0, sell: 0, net: 0 }, dii: { buy: 0, sell: 0, net: 0 } },
  sentiment: 50,
  orders: [],
  notifications: [],
  totalPnl: 0,
  pnlByBroker: {},
  activeBrokerId: "dhan",
  mainBrokerId: "dhan",
  brokers: [
    {
      id: "dhan",
      name: "Dhan",
      vendor: "Dhan",
      color: "#0f9d58",
      main: true,
      connected: true,
      active: true,
      mode: "idle",
      clientId: "",
      funds: 0,
      marginUsed: 0,
      status: "CONNECTED",
      segments: ["EQ", "FNO"],
      liveFeed: false,
    },
    {
      id: "zerodha",
      name: "Zerodha Kite",
      vendor: "Zerodha",
      color: "#f6461a",
      connected: false,
      active: false,
      mode: "sandbox",
      clientId: "",
      funds: 0,
      marginUsed: 0,
      status: "DISCONNECTED",
      segments: ["EQ", "FNO", "COM"],
    },
    {
      id: "kotak",
      name: "Kotak Neo",
      vendor: "Kotak",
      color: "#0033a0",
      connected: false,
      active: false,
      mode: "sandbox",
      clientId: "",
      funds: 0,
      marginUsed: 0,
      status: "DISCONNECTED",
      segments: ["EQ", "FNO"],
    },
    {
      id: "fyers",
      name: "Fyers",
      vendor: "Fyers",
      color: "#111827",
      connected: false,
      active: false,
      mode: "sandbox",
      clientId: "",
      funds: 0,
      marginUsed: 0,
      status: "DISCONNECTED",
      segments: ["EQ", "FNO"],
    },
  ],
  marketStatus: "OPEN",
  dhanFeed: {
    live: false,
    source: "idle",
    lastTickAt: null,
    error: null,
    tokenHint: null,
    profileName: null,
    quoteCount: 0,
  },
  optionMeta: {
    symbol: "NIFTY",
    expiry: "2026-08-25",
    expiries: ["2026-08-25", "2026-09-01", "2026-09-08"],
    spot: 24580.25,
    pcr: 0.86,
    maxPain: 24500,
    atmIv: 12.4,
    source: "demo",
    expiryLabel: "Tue, 25 Aug 2026",
    underlyings: [
      { id: "NIFTY", label: "NIFTY", lot: 65 },
      { id: "BANKNIFTY", label: "BANKNIFTY", lot: 30 },
      { id: "FINNIFTY", label: "FINNIFTY", lot: 60 },
      { id: "SENSEX", label: "SENSEX", lot: 20 },
    ],
  },
};
